version: "3"

services:
  server:
    build: .
    image: frugal-server-dev
    command: sh /home/app/start.sh
    expose:
      - 2000
    ports:
      - "2000:2000"
    volumes:
      - .:/home/app
      - /home/app/node_modules/
    depends_on:
      - es01
    networks:
      - server

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - server

networks:
  server:
