version: "3"

services:
  server:
    build: .
    image: frugal-server-test
    command: sh /home/app/test.sh
    expose:
      - 2000
      - 9229
    ports:
      - "2000:2000"
      - "9229:9229"
    volumes:
      - .:/home/app
      - /home/app/node_modules/
    depends_on:
      - es01
    networks:
      - server

  es01:
    image: blacktop/elasticsearch:7.4
    ulimits:
      memlock: -1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - server

networks:
  server:
