// const types = [
//   "21+",
//   "happy hour",
//   "food",
//   "brunch",
//   "burgers",
//   "tacos",
//   "games",
//   "bowling",
//   "ping pong",
//   "karaoke",
//   "trivia",
//   "beer",
//   "wine",
//   "sangria",
//   "wells",
//   "mimosas",
//   "margs",
//   "shots",
//   "martinis",
//   "alcohol",
//   "comedy",
//   "stand up",
//   "open mic",
//   "live music"
// ];
